pizza/urls.py
""" url's for the pizza app"""
from django.urls import path

from . import views

app_name = 'pizza'
urlpatterns = [
    #homepage
    path('', views.index, name = 'index'),
    #Overview page og Pizza's
    path('pizzas/', views.pizzas, name = 'pizzas'),
    #detail page of pizza
    path('pizza/<int:pizza_id>/', views.pizza, name = 'pizza'),
]

pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizza.urls')),
]

pizza/models.py
from django.db import models

# Create your models here.
class Pizza(models.Model):
    """Name of a Pizza"""
    text = models.CharField(max_length=100)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representation of the model.""" 
        return self.text


class Topping(models.Model):
    """ The toppings per pizza."""
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    text = models.TextField(max_length=100)

    def __str__(self):
        """Return a string representation of the topping."""
        if len(self.text) > 50:
            return f"{self.text[:50]}..."
        else:
            return f"{self.text}"

pizza/views.py
from django.shortcuts import render

from .models import Pizza, Topping

# Create your views here.
def index(request):
    """The home page for the Pizza"""
    return render(request,'pizza/index.html')
    

def pizzas(request): 
    """Show all topics."""
    pizzas = Pizza.objects.order_by('date_added')
    context = {'pizzas': pizzas}
    return render(request, 'pizza/pizzas.html', context)


def pizza(request, pizza_id):
    """Show a single Pizza and all its toppings."""
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.topping_set.order_by('text')
    context = {'pizza': pizza, 'toppings': toppings}
    return render(request, 'pizza/pizza.html', context)

pizza/templates/pizza/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'pizza/style.css' %}">
    
    <title>
        {% block title %}Remco's Pizza house
        {% endblock title%}
    </title>
</head>

<body>
    <div class="sidebar">
        {% block sidebar %}
        <ul>
            <li><a href="{% url 'pizza:index' %}">Home</a></li>
            <li><a href="{% url 'pizza:pizzas' %}">Pizzas</a></li>
        </ul>
        {% endblock sidebar %}
    </div>

    <div class="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

pizza/templates/pizza/index.html
{% extends "pizza/base.html" %} 

{% block content %}
<p>An easy way to order your Pizza's</p>
{% endblock content %}

pizza/templates/pizza/pizza.html
{% extends "pizza/pizzas.html" %} 
  
{% block content %}
  <H1>Pizza: {{ pizza }}</H1>
  <p>Toppings:</p>
  <ul>
    {% for topping in toppings %}
      <li>
        <p>{{ topping.text|linebreaks }}</p>
      </li>
    {% empty %}
       <li>There are no entries for this topic yet.</li>
    {% endfor %}
  </ul>
{% endblock content %}

pizza/templates/pizza/pizzas.html
{% extends "pizza/base.html" %} 

{% block content %}
<H3>These are our Pizzas</H3>
<ul>
    {% for pizza in pizzas %}
      <li>
        <a href="{% url 'pizza:pizza' pizza.id %}">{{ pizza }}</a>
      </li>
    {% empty %}
      <li>No topics have been added yet.</li>
    {% endfor %}
  </ul>
{% endblock content %}